pipeline {
    agent {
        label 'AGENT-1'
    }

    options {
        timeout(time: 30, unit: 'MINUTES') // abort if build exceeds 30 minutes
        disableConcurrentBuilds()           // prevent concurrent builds
        ansicolor('xterm')                   // enable ANSI color support
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select ACTION')
    }

    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        
    }

    post { 
        always { 
            echo "This section will always execute regardless of the build result"
            deleteDir() // clean workspace
        }
        success { 
            echo "Pipeline succeeded!"
        }
        failure { 
            echo "Pipeline failed!"
        }
    }
}