pipeline {
    agent {
        label 'AGENT-1'
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select ACTION')
    }

    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        stage('Apply or Destroy') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                       cd 10-sg
                       if [ "${params.ACTION}" = "apply" ]; then
                          terraform apply -auto-approve tfplan
                       elif [ "${params.ACTION}" = "destroy" ]; then
                          terraform destroy -auto-approve
                       fi
                    """
                }
            }
        }

        stage ('Destroy VPC') {
            when {
                expression { params.ACTION == 'destroy' }
            }
            steps {
                build job: '00-vpc', parameters: [string(name: 'ACTION', value: 'destroy')]
            }
        }

        stage ('Parallel In Sequential') {
            when {
                expression { params.ACTION == 'apply' }
            }
            parallel {
                stage('Trigger Bastion') {
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: 'apply')]
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        build job: '40-eks', parameters: [string(name: 'ACTION', value: 'apply')]
                    }
                }
            }
        } 

    } 
    post { 
        always { 
            echo "This section will always execute regardless of the build result"
            deleteDir()
        }
        success { 
            echo "Pipeline succeeded!"
        }
        failure { 
            echo "Pipeline failed!"
        }
    }
}